// <auto-generated />
namespace LocalFileWebService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updatesourcethumbnailpath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesourcethumbnailpath));
        
        string IMigrationMetadata.Id
        {
            get { return "202501070454106_update-source-thumbnail-path"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
